import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Evidence} from '../src/evidence.js';
import {records} from '../src/history.js';
import {recordAcceptance,queryOperationsMetrics,recordCostEstimate} from '../src/metrics/index.js';
const scope={from:'2000-01-01T00:00:00Z',to:'2100-01-01T00:00:00Z',asOf:'2100-01-01T00:00:00Z',source:'synthetic' as const};
const root=()=>mkdtempSync(join(tmpdir(),'durio-cost-fault-'));
function task(root:string,id:string,kind='coding',status='completed'){
 const e=new Evidence(root,id);e.append('task.accepted',{taskId:id,sessionId:id,workspace:'/fixture',input:'known facts',origin:{kind,source:'synthetic'}});e.append('run.started',{});return{e,close(reason?:string){e.append('run.closed',{status,reason,cleanup:'confirmed',observation:'ok',lifecycle:{storage:'closed'},usage:{completeness:'known'}});e.close();}};}
function request(e:Evidence,id:string,amount:number,options:{allocation?:string;purpose?:string;error?:boolean}={}){
 e.append('model.intent',{attemptId:id,durableTaskId:'known-generation-operation',model:{provider:'fixture',id:'fixed'},purpose:options.purpose??'generation',allocation:options.allocation??'task'});
 e.append('model.dispatch',{attemptId:id,transportEntered:true});e.append('model.response',{attemptId:id,usage:'reported',completeness:'complete',message:{stopReason:options.error?'error':'stop',...(options.error?{errorMessage:'controlled service error'}:{}),usage:{input:1,output:1,cacheRead:0,cacheWrite:0,totalTokens:2,cost:{total:amount}}}});
}
function price(root:string,id:string,amount:number,currency='CNY'){
 const refs=[...records(root,{runId:id,kinds:['model.intent','model.response']})];
 for(let i=0;i<refs.length;i+=2)recordCostEstimate(root,{id:`price-${id}-${i}`,requestSource:refs[i].id,amount:amount/(refs.length/2),currency,price:{source:'known worked-example tariff',version:'fixture-v1',provider:'fixture',model:'fixed',effectiveAt:'2000-01-01T00:00:00Z'},usageSources:[refs[i+1].id],reason:'Explicit known facts, not provider billing'});
}
function pass(root:string,id:string){const source={kind:'human' as const,actor:'fixture',statement:'All necessary requirements met',refs:[]};const evidence=[...records(root,{runId:id,kinds:['run.closed']})].map(r=>r.id);recordAcceptance(root,{type:'requirements',id:`req-${id}`,taskId:id,source,ruleVersion:'r1',necessary:[{id:'goal',description:'agreed result'}]});recordAcceptance(root,{type:'result',id:`result-${id}`,taskId:id,source,requirementsId:`req-${id}`,evidence});recordAcceptance(root,{type:'judgment',id:`pass-${id}`,taskId:id,source,requirementsId:`req-${id}`,resultId:`result-${id}`,findings:[{requirementId:'goal',outcome:'PASS',evidence}],validity:'valid'});}
test('complete full-sample CNY 80 / current S4 = 20 includes failure/retry/cancel/auto-compaction, and total 118 deduplicates views',()=>{
 const r=root();for(let n=0;n<10;n++){const id=`t${n}`,t=task(r,id,'coding',n===4?'failed':n===5?'cancelled':'completed');request(t.e,id,8,{purpose:n===6?'compaction':'generation',error:n===4});t.close();price(r,id,n<4?12.5:5);if(n<4)pass(r,id);}
 for(const [id,kind,amount]of [['evaluation','eval',20],['analysis','improve',10],['manual','maintenance',5],['shared','shared',3]] as const){const t=task(r,id,kind);request(t.e,id,amount,{allocation:kind==='maintenance'?'maintenance':kind});t.close();price(r,id,amount);}
 const report=queryOperationsMetrics(r,scope);assert.equal(report.sample.counts.S,4);assert.equal(report.costs.sample.currencies.CNY.knownAmount,80);assert.equal(report.costs.sample.currencies.CNY.perSuccess.value,20);assert.equal(report.costs.sample.state,'complete');assert.equal(report.costs.period.currencies.CNY.knownAmount,118);assert.equal(report.costs.requests.length,14);
 const e=new Evidence(r,'t9');e.append('recovery.started',{});e.append('model.intent',{attemptId:'missing',allocation:'task',purpose:'generation'});e.append('model.dispatch',{attemptId:'missing',transportEntered:true});e.close();const partial=queryOperationsMetrics(r,scope);assert.equal(partial.costs.sample.state,'partial');assert.equal(partial.costs.sample.currencies.CNY.perSuccess.value,null);assert.equal(partial.costs.sample.currencies.CNY.perSuccess.knownPartPerSuccess,20);
});
test('fault example retains recovered errors, 2/8 task faults, 1/8 terminations, and separate physical model/tool attempt coverage',()=>{
 const r=root();for(let n=0;n<8;n++){const t=task(r,`f${n}`,'coding',n===1?'failed':'completed');if(n===0){request(t.e,'retry-1',1,{error:true});request(t.e,'retry-2',1,{error:true});}if(n===7){t.e.append('model.intent',{attemptId:'unknown',allocation:'task'});t.e.append('model.dispatch',{attemptId:'unknown',transportEntered:true});}else request(t.e,`normal-${n}`,1);
 if(n>=1&&n<=6){if(n===6)t.e.append('acceptance.requirements',{taskId:`f${n}`,necessary:[{id:'negative-case',check:{command:'test known counterexample',passExitCodes:[0],failExitCodes:[1]}}]});t.e.append('tool.intent',{attemptId:`tool-${n}`,tool:'bash',args:{command:'test known counterexample'}});t.e.append('tool.dispatch',{attemptId:`tool-${n}`});if(n===1)t.e.append('tool.error',{attemptId:`tool-${n}`,error:'spawn failed'});else{t.e.append('shell.completed',{toolAttempt:{attemptId:`tool-${n}`},acquired:{exitCode:n===6?1:0}});t.e.append('tool.result',{attemptId:`tool-${n}`,result:{isError:n===6}});}}t.close(n===1?'spawn failed':undefined);}
 const report=queryOperationsMetrics(r,scope);assert.deepEqual(report.faults.tasks.counts,{B:8,F:2,Zf:5,Uf:1,faultTerminated:1});assert.equal(report.faults.tasks.observedFaults.value,0.25);assert.equal(report.faults.tasks.coverage.value,0.875);assert.deepEqual(report.faults.tasks.logicalRange,{lower:0.25,upper:0.375,interpretation:'logical bounds, not a statistical confidence interval'});assert.equal(report.faults.events.filter(e=>e.recovered).length,2);assert.equal(report.faults.attempts.model.started,10);assert.equal(report.faults.attempts.model.counts.error,2);assert.equal(report.faults.attempts.model.counts.normal,7);assert.equal(report.faults.attempts.model.coverage.value,0.9);assert.equal(report.faults.attempts.tool.started,6);assert.equal(report.faults.attempts.tool.counts.error,1);assert.equal(report.faults.attempts.tool.rawNonzero,1);
});
test('unknown ownership, usage and price keep known-part/S partial; S0 stays N/A; historical and conflicting re-estimates remain inspectable',()=>{
 const r=root(),t=task(r,'ordinary');request(t.e,'one',1);t.close();price(r,'ordinary',5);pass(r,'ordinary');const original=queryOperationsMetrics(r,scope);
 const unassigned=new Evidence(r,'unassigned');unassigned.append('model.intent',{attemptId:'lost',allocation:'unknown'});unassigned.append('model.dispatch',{attemptId:'lost',transportEntered:true});unassigned.close();
 const partial=queryOperationsMetrics(r,scope);assert.equal(partial.costs.sample.state,'partial');assert.equal(partial.costs.sample.currencies.CNY.perSuccess.value,null);assert.equal(queryOperationsMetrics(r,{...scope,through:original.sample.scope.through}).id,original.id);
 const originalEstimate=original.costs.requests[0].history.at(-1),input={...originalEstimate.input,id:'revised',amount:6,revisionOf:originalEstimate.id,reason:'Reprice using explicit source revision',price:{...originalEstimate.price,version:'v2'}};
 recordCostEstimate(r,input);assert.equal(recordCostEstimate(r,input).repeated,true);assert.equal(queryOperationsMetrics(r,scope).costs.requests.find(c=>c.runId==='ordinary')!.amount,6);recordCostEstimate(r,{...input,id:'fork',amount:7});const conflict=queryOperationsMetrics(r,scope).costs.requests.find(c=>c.runId==='ordinary')!;assert.equal(conflict.amount,null);assert.match(conflict.gaps.join(' '),/conflict/);
 const empty=queryOperationsMetrics(r,{...scope,taskType:'missing'});assert.equal(empty.sample.counts.S,0);assert.equal(empty.costs.sample.perSuccessState,'N/A');
 const sharedRoot=root(),shared=task(sharedRoot,'shared-coding');request(shared.e,'shared-request',2,{allocation:'shared'});shared.close();price(sharedRoot,'shared-coding',2);pass(sharedRoot,'shared-coding');const sharedReport=queryOperationsMetrics(sharedRoot,scope);assert.equal(sharedReport.costs.sample.requestIds.length,0);assert.equal(sharedReport.costs.sample.state,'unknown');assert.equal(sharedReport.costs.period.currencies.CNY.knownAmount,2);assert.equal(sharedReport.costs.requests[0].kind,'shared');assert.match(sharedReport.costs.sample.gaps[0].reason,/shared/);
});
test('normal managed cancellation is covered, errors before cancellation survive, and unrelated later success does not prove recovery or fault termination',()=>{
 const r=root();for(const prior of [false,true]){const t=task(r,`cancel-${prior}`,'coding','aborted');if(prior)request(t.e,'prior',1,{error:true});t.e.append('model.intent',{attemptId:'cancelled',allocation:'task'});t.e.append('model.dispatch',{attemptId:'cancelled',transportEntered:true});t.e.append('run.abort-intent',{});t.e.append('model.dispatch-failed',{attemptId:'cancelled',dispatched:true,reason:'AbortError'});t.e.append('model.response',{attemptId:'cancelled',usage:'unknown',message:{stopReason:'aborted',errorMessage:'AbortError'}});t.e.append('lifecycle.abort-settled',{});t.close();}
 const unrelated=task(r,'unrelated','coding','failed');unrelated.e.append('tool.intent',{attemptId:'bad',durableTaskId:1,callId:'one',tool:'write'});unrelated.e.append('tool.dispatch',{attemptId:'bad'});unrelated.e.append('tool.error',{attemptId:'bad',error:'write failed'});unrelated.e.append('tool.intent',{attemptId:'good',durableTaskId:2,callId:'two',tool:'read'});unrelated.e.append('tool.dispatch',{attemptId:'good'});unrelated.e.append('tool.result',{attemptId:'good',result:{}});unrelated.close('different terminal failure');
 const report=queryOperationsMetrics(r,scope);assert.equal(report.faults.attempts.model.counts.cancelled,2);assert.equal(report.faults.attempts.model.counts.error,1);assert.equal(report.faults.tasks.members.find(m=>m.taskId==='cancel-false')!.category,'Zf');assert.equal(report.faults.tasks.members.find(m=>m.taskId==='cancel-true')!.category,'F');const wrong=report.faults.tasks.members.find(m=>m.taskId==='unrelated')!;assert.equal(wrong.recoveredEvents,0);assert.equal(wrong.faultTerminated,false);assert.equal(wrong.faultTermination,'unknown');
});
test('period occurrence and admission accumulation use distinct windows and currencies; manual compaction never inherits coding ownership',()=>{
 const r=root(),old=task(r,'old');request(old.e,'early',1);old.close();price(r,'old',2);
 const from=new Date().toISOString();const fresh=task(r,'fresh');request(fresh.e,'fresh',1);request(fresh.e,'automatic',1,{purpose:'compaction'});request(fresh.e,'manual',1,{purpose:'compaction',allocation:'maintenance'});fresh.close();pass(r,'fresh');
 const later=new Evidence(r,'old');request(later,'later',1);later.close();
 const freshIntents=[...records(r,{runId:'fresh',kinds:['model.intent']})],freshResponses=[...records(r,{runId:'fresh',kinds:['model.response']})];
 for(const [i,ref]of freshIntents.entries())recordCostEstimate(r,{id:`different-${i}`,requestSource:ref.id,amount:i===2?7:3,currency:i===2?'EUR':'CNY',price:{provider:'fixture',model:'fixed',source:'explicit fixture tariff',version:'v1',effectiveAt:'2000-01-01T00:00:00Z'},usageSources:[freshResponses[i].id],reason:'Known currency fixture'});
 const report=queryOperationsMetrics(r,{...scope,from});assert.equal(report.sample.counts.N,1);assert.equal(report.costs.sample.currencies.CNY.knownAmount,6);assert.equal(report.costs.sample.currencies.EUR,undefined);assert.equal(report.costs.period.currencies.EUR.knownAmount,7);assert.equal(report.costs.period.requestIds.length,4);assert.equal(report.costs.sample.requestIds.length,2);assert.equal(report.costs.period.currencies.USD.knownAmount,1);
});
test('owned child eval follows a scoped fixed plan and parent snapshot, counts trusted requests once, and never widens to later child work',()=>{
 const parent=root(),directory=join(parent,'validation'),child=join(directory,'prompt.v1','check-0','eval-data');const p=task(parent,'analysis','improve');p.close();
 const e=new Evidence(parent,'analysis');e.append('improve.decision',{id:'decision',decision:{directory,groups:[{id:'prompt.v1',checks:[{kind:'fresh'}]}]}});e.close();const decision=[...records(parent,{kinds:['improve.decision']})][0];
 const c=new Evidence(child,'plan');c.append('eval.plan',{id:'plan',mode:'offline',model:{provider:'fixture',id:'fixed'},trials:[{id:'trial',side:'candidate'}],price:{version:'v1',source:'fixed fixture',currency:'CNY',perMillionTokens:100000}});c.append('provider.dispatch',{id:'outer',operationId:'trial',purpose:'eval-runtime'});c.append('provider.http',{id:'outer',status:200});c.append('provider.bytes',{id:'outer',bytes:c.blob('data: {"usage":{"prompt_tokens":6,"completion_tokens":4}}\n')});c.append('budget.settle',{id:'outer',tokens:10,status:'returned'});c.append('eval.closed',{});c.close();const plan=[...records(child,{kinds:['eval.plan']})][0],through=[...records(child)].at(-1)!.seq;
 const link=new Evidence(parent,'analysis');link.append('improve.eval',{id:'decision',groupId:'prompt.v1',index:0,kind:'eval',dataRoot:child,planId:'plan',planSource:{scope:'child-data-root',dataRoot:child,sequence:plan.seq,digest:plan.ref.sha256},parent:{dataRoot:parent,decisionSource:decision.id,decisionId:'decision'}});link.close();
 const pending=queryOperationsMetrics(parent,scope);assert.equal(pending.costs.requests.length,0);assert.match(pending.ownedChildren.gaps[0].reason,/no retained child/);
 const check=new Evidence(parent,'analysis');check.append('improve.check',{id:'decision',groupId:'prompt.v1',index:0,dataRoot:child,planId:'plan',reportOrigin:{dataRoot:child,planId:'plan'},reportDocument:check.blob(JSON.stringify({planId:'plan',planSource:plan.id,asOf:through}))});check.close();
 const report=queryOperationsMetrics(parent,scope);assert.equal(report.sample.counts.N,0);assert.equal(report.costs.requests.length,1);assert.equal(report.costs.period.currencies.CNY.knownAmount,1);assert.equal(report.costs.requests[0].kind,'eval');assert.equal(report.costs.requests[0].parentImprove?.decisionId,'decision');assert.equal(report.faults.separate.otherWorkAttempts.length,1);assert.equal(report.ownedChildren.snapshots[0].through,through);
 assert.throws(()=>recordCostEstimate(child,{id:'wrong-model',requestSource:report.costs.requests[0].source,amount:1,currency:'CNY',price:{source:'fixture',version:'v1',effectiveAt:'2000-01-01T00:00:00Z',provider:'fixture',model:'other'},usageSources:report.costs.requests[0].usageSources,reason:'reject changed model'}),/PRICE_MODEL_SCOPE_CHANGED/);
 const later=new Evidence(child,'plan');later.append('provider.dispatch',{id:'later',operationId:'trial',purpose:'eval-runtime'});later.close();assert.equal(queryOperationsMetrics(parent,{...scope,through:report.sample.scope.through}).id,report.id);
});
