import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,unlinkSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {Evidence} from '../src/evidence.js';
import {records} from '../src/history.js';
import {queryFeedbackMetrics,recordFeedback} from '../src/metrics/index.js';
const scope={from:'2000-01-01T00:00:00Z',to:'2100-01-01T00:00:00Z',asOf:'2100-01-01T00:00:00Z',source:'synthetic' as const};
function fixture(n=10){const root=mkdtempSync(join(tmpdir(),'durio-feedback-'));for(let i=0;i<n;i++){const e=new Evidence(root,`r${i}`);e.append('task.accepted',{taskId:`t${i}`,sessionId:`s${i}`,workspace:'/fixture',input:'Deliver the original agreed result',origin:{kind:'coding',source:'synthetic'}});if(i<8){e.append('run.started',{});e.append('execution.artifact',{id:'actual-v1'});e.append('run.closed',{status:'completed',cleanup:'confirmed',answer:'Delivered conclusion'});}e.close();}return root;}
const refs=(root:string,i:number)=>[...records(root,{runId:`r${i}`})];
const source={kind:'human' as const,actor:'user',statement:'I corrected the ignored original requirement during this work',refs:[] as string[]};
function correction(root:string,i:number,id:string){const r=refs(root,i);return recordFeedback(root,{type:'observation',id,taskId:`t${i}`,dimension:'intervention',meaning:'correction',source,requirements:[r[0].id],originalRequirement:'unmet',correction:'started',occurredAt:r[1].at});}
test('confirmed example 4 retains 2/8 interventions, 3 events, 3 full-stage negatives and 3 unknowns',()=>{const root=fixture();correction(root,0,'a');correction(root,0,'b');correction(root,1,'c');for(const i of [2,3,4]){const r=refs(root,i);recordFeedback(root,{type:'observation',id:`n${i}`,taskId:`t${i}`,dimension:'intervention',meaning:'none',source:{...source,statement:'No human correction or takeover throughout this task'},requirements:[r[0].id],occurredAt:r[3].at,coverage:{from:r[1].at,to:r[3].at}});}const report=queryFeedbackMetrics(root,scope);assert.deepEqual(report.intervention.counts,{Ni:8,I:2,Z:3,U:3,events:3,unstarted:2,open:0,openPositive:0});assert.equal(report.intervention.rate.value,.25);assert.equal(report.intervention.coverage.value,.625);assert.deepEqual(report.intervention.logicalRange,[.25,.625]);assert.equal(report.intervention.completeRate,'unknown');assert.equal(queryFeedbackMetrics(root,{...scope,source:'ordinary'}).intervention.rate.state,'N/A');});
const DAY=24*60*60*1000,epoch=Date.parse('2026-01-01T00:00:00Z');
const at=(day:number)=>new Date(epoch+day*DAY).toISOString();
function clockFixture(t:any,deliveries:number[],statuses:string[]=[]){const root=mkdtempSync(join(tmpdir(),'durio-deliveries-'));t.mock.timers.enable({apis:['Date'],now:epoch});for(let i=0;i<deliveries.length;i++){const e=new Evidence(root,`r${i}`);e.append('task.accepted',{taskId:`t${i}`,sessionId:`s${i}`,workspace:'/fixture',input:'Original requirement: a correct result',origin:{kind:'coding',source:'synthetic'}});e.append('run.started',{});e.append('execution.artifact',{id:'actual-v1'});e.append('model.response',{answer:'Intermediate model claim: done'});e.close();}for(const day of [...new Set(deliveries)].sort((a,b)=>a-b)){t.mock.timers.setTime(epoch+day*DAY);for(let i=0;i<deliveries.length;i++)if(deliveries[i]===day){const e=new Evidence(root,`r${i}`);e.append('run.closed',{status:statuses[i]??'completed',cleanup:'confirmed',answer:'Host delivered result'});e.close();}}return root;}
function rework(root:string,i:number,id:string,day:number|null){return recordFeedback(root,{type:'observation',id,taskId:`t${i}`,dimension:'rework',meaning:'correction',source:{...source,statement:'The original requirement was not met; correction is requested'},requirements:[refs(root,i)[0].id],originalRequirement:'unmet',correction:'requested',occurredAt:day===null?null:at(day)});}
test('confirmed example 5 uses first delivery independent of admission and acceptance; late evidence revises without changing old snapshots',t=>{const root=clockFixture(t,[1,2,3,9,10]);t.mock.timers.setTime(epoch+11*DAY);const r0=refs(root,0),r1=refs(root,1);rework(root,0,'a',4);recordFeedback(root,{type:'observation',id:'b-none',taskId:'t1',dimension:'rework',meaning:'none',source:{...source,statement:'No rework required throughout the complete seven-day window'},requirements:[r1[0].id],occurredAt:at(11),coverage:{from:at(2),to:at(9)}});rework(root,3,'d',10);const requested={from:at(1),to:at(11),asOf:at(11),source:'synthetic' as const};const report=queryFeedbackMetrics(root,requested);assert.deepEqual(report.rework.counts,{Nr:3,Rr:1,Zr:1,Ur:1,events:1,immature:2,immaturePositive:1});assert.equal(report.intervention.counts.Ni,0,'all admissions predate selection while deliveries remain selected');assert.deepEqual(report.rework.logicalRange,[1/3,2/3]);assert.ok(report.rework.tasks.every(t=>t.acceptance==='unknown'));assert.equal(report.rework.tasks[0].delivery?.source,r0.at(-1)!.id);const before=queryFeedbackMetrics(root,{...requested,asOf:at(10)});assert.equal(before.rework.counts.Rr,0,'day-11 evidence was not known on day 10');assert.equal(before.rework.counts.Ur,3);const oldId=report.id;rework(root,2,'c-late',6);assert.equal(queryFeedbackMetrics(root,requested).rework.counts.Rr,2);assert.equal(queryFeedbackMetrics(root,{...requested,through:report.scope.through}).id,oldId);const e=new Evidence(root,'r0');e.append('recovery.closed',{result:{status:'completed',cleanup:'confirmed',answer:'Corrected redelivery'}});e.close();const later=queryFeedbackMetrics(root,requested);assert.equal(later.rework.tasks[0].window.from,at(1));assert.equal(later.rework.tasks[0].redeliveries.length,1);});

test('seven-day window is half-open, maturity is inclusive, unknown times and pre-delivery/new scope remain visible',t=>{const root=clockFixture(t,[1,1,1,1,1,1,1]);t.mock.timers.setTime(epoch+10*DAY);rework(root,0,'at-start',1);rework(root,1,'just-before-end',8-1/DAY);rework(root,2,'at-end',8);rework(root,3,'unknown-time',null);rework(root,4,'predelivery',.5);recordFeedback(root,{type:'observation',id:'new-scope',taskId:'t5',dimension:'rework',meaning:'new-requirement',source,requirements:[refs(root,5)[0].id],occurredAt:at(3)});recordFeedback(root,{type:'observation',id:'unverified-complaint',taskId:'t6',dimension:'rework',meaning:'complaint',source,requirements:[refs(root,6)[0].id],occurredAt:at(3)});const report=queryFeedbackMetrics(root,{...scope,asOf:at(10)});assert.equal(report.rework.counts.Rr,2);assert.equal(report.rework.counts.Ur,5);assert.equal(report.rework.tasks[2].events[0].position,'outside-window');assert.equal(report.rework.tasks[3].events[0].position,'unknown-time');assert.equal(report.rework.tasks[4].events[0].position,'before-window');assert.equal(report.rework.tasks[5].events[0].classification,'excluded');assert.equal(report.rework.tasks[6].events[0].classification,'unknown');const immature=queryFeedbackMetrics(root,{...scope,asOf:at(8-1/DAY)});assert.equal(immature.rework.counts.Nr,0);assert.equal(immature.rework.rate.state,'N/A');assert.equal(queryFeedbackMetrics(root,{...scope,asOf:at(8)}).rework.counts.Nr,7);});

test('normal consent, partial absence, PASS-like ambiguity and completed logs do not erase unknown; open positives remain separate',t=>{const root=clockFixture(t,[1,1,1,1]);t.mock.timers.setTime(epoch+10*DAY);for(const [i,meaning] of ['normal-authorization','clarification','improve-choice','unknown'].entries())recordFeedback(root,{type:'observation',id:`normal-${i}`,taskId:`t${i}`,dimension:'intervention',meaning:meaning as 'normal-authorization'|'clarification'|'improve-choice'|'unknown',source:{...source,statement:i===3?'Thanks; passed':'Normal interaction'},requirements:[refs(root,i)[0].id],occurredAt:at(.5)});recordFeedback(root,{type:'observation',id:'partial',taskId:'t0',dimension:'rework',meaning:'none',source,requirements:[refs(root,0)[0].id],occurredAt:at(3),coverage:{from:at(1),to:at(3)}});const e=new Evidence(root,'open');e.append('task.accepted',{taskId:'open',sessionId:'open',workspace:'/fixture',input:'Original work',origin:{kind:'coding',source:'synthetic'}});e.append('run.started',{});e.close();const ref=[...records(root,{runId:'open'})][0];recordFeedback(root,{type:'observation',id:'open-rescue',taskId:'open',dimension:'intervention',meaning:'correction',source,requirements:[ref.id],originalRequirement:'unmet',correction:'started',occurredAt:at(10)});const report=queryFeedbackMetrics(root,{...scope,asOf:at(10)});assert.deepEqual(report.intervention.counts,{Ni:4,I:0,Z:0,U:4,events:0,unstarted:0,open:1,openPositive:1});assert.equal(report.rework.counts.Ur,4);});

test('failed diagnostics and intermediate claims are not delivery; recovery can supply the first normal unaccepted conclusion',t=>{const root=clockFixture(t,[1],['failed']);t.mock.timers.setTime(epoch+2*DAY);const e=new Evidence(root,'r0');e.append('recovery.started',{});e.append('recovery.closed',{result:{status:'completed',cleanup:'confirmed',answer:'Final analysis conclusion; no file edits needed'}});e.close();const r=queryFeedbackMetrics(root,{...scope,asOf:at(2)});assert.equal(r.rework.tasks[0].delivery?.at,at(2));assert.equal(r.rework.tasks[0].acceptance,'unknown');assert.equal(r.rework.counts.immature,1);assert.equal(queryFeedbackMetrics(root,{...scope,asOf:at(1)}).rework.tasks.length,0);});

test('explicit revisions/withdrawals retain originals, idempotent feedback and unknown conflicts without reviving stale classifications',t=>{const root=clockFixture(t,[1]);t.mock.timers.setTime(epoch+10*DAY);const receipt=rework(root,0,'original',3),r=refs(root,0);const old=queryFeedbackMetrics(root,{...scope,asOf:at(10)});const changed={type:'observation' as const,id:'corrected',taskId:'t0',dimension:'rework' as const,meaning:'new-requirement' as const,source:{...source,statement:'Correction: this request was new scope, not original required work'},requirements:[r[0].id],occurredAt:at(3),revisionOf:'original',reason:'User corrected the original classification'};recordFeedback(root,changed);assert.equal(recordFeedback(root,changed).repeated,true);assert.throws(()=>recordFeedback(root,{...changed,reason:'different'}),/ID conflicts/);let report=queryFeedbackMetrics(root,{...scope,asOf:at(10)});assert.equal(report.rework.counts.Rr,0);assert.ok(report.rework.tasks[0].feedback.history.some(h=>h.source===receipt.source&&h.superseded));recordFeedback(root,{type:'withdraw',id:'withdraw',taskId:'t0',source,targets:['corrected'],reason:'Replacement also unsupported'});assert.equal(queryFeedbackMetrics(root,{...scope,asOf:at(10)}).rework.counts.Rr,0);assert.equal(queryFeedbackMetrics(root,{...old.scope}).id,old.id);recordFeedback(root,{...changed,id:'fork',meaning:'correction',originalRequirement:'unmet',correction:'requested'});report=queryFeedbackMetrics(root,{...scope,asOf:at(10)});assert.equal(report.rework.counts.Rr,0);assert.ok(report.rework.tasks[0].events.some(e=>e.conflict));});

test('a whole-window absence cannot hide unknown-time corrective evidence; known out-of-window corrections do not defeat it',t=>{const root=clockFixture(t,[1,1]);t.mock.timers.setTime(epoch+10*DAY);for(let i=0;i<2;i++)recordFeedback(root,{type:'observation',id:`none-${i}`,taskId:`t${i}`,dimension:'rework',meaning:'none',source,requirements:[refs(root,i)[0].id],occurredAt:at(10),coverage:{from:at(1),to:at(8)}});rework(root,0,'unknown-time',null);rework(root,1,'outside',9);const report=queryFeedbackMetrics(root,{...scope,asOf:at(10)});assert.equal(report.rework.tasks[0].state,'Ur');assert.equal(report.rework.tasks[1].state,'Zr');});

test('unknown scope, duplicate receipt of the same original feedback and unavailable revision originals do not produce certain counts',t=>{const root=clockFixture(t,[1]);t.mock.timers.setTime(epoch+10*DAY);const e=new Evidence(root,'r0');const seq=e.append('user.feedback',{text:'Original requirement unmet; please fix it',occurredAt:at(3)});e.close();const original=[...records(root,{after:seq-1,through:seq})][0];const input={type:'observation' as const,id:'feedback',taskId:'t0',dimension:'rework' as const,meaning:'correction' as const,source:{...source,refs:[original.id]},requirements:[refs(root,0)[0].id],originalRequirement:'unmet' as const,correction:'requested' as const,occurredAt:at(3)};recordFeedback(root,input);const duplicate=recordFeedback(root,{...input,id:'same-message-received-again'});assert.equal(duplicate.repeated,true);assert.equal(queryFeedbackMetrics(root,{...scope,asOf:at(10)}).rework.counts.events,1);assert.throws(()=>recordFeedback(root,{...input,id:'wrong-requirement',requirements:[original.id]}),/original requirements/);recordFeedback(root,{type:'withdraw',id:'withdraw',taskId:'t0',source,targets:['feedback'],reason:'Feedback was incorrectly attributed'});const withdrawal=[...records(root,{kinds:['feedback.withdraw']})][0];unlinkSync(join(root,'objects',withdrawal.ref.sha256));const report=queryFeedbackMetrics(root,{...scope,asOf:at(10)});assert.equal(report.rework.counts.Rr,0);assert.equal(report.rework.counts.Ur,1);assert.equal(report.rework.tasks[0].feedback.missing.length,1);});
