#!/usr/bin/env node
/** No real provider calls and no durable paid authorization. */
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {installed,json,save,file,sha,verifyInstallation} from './common.mjs';
const [installArg,linuxArg,outputArg,identityArg]=process.argv.slice(2);
if(!identityArg)throw Error('Usage: prepare.mjs INDEPENDENT_INSTALL LINUX_RUNTIME NEW_OUTPUT PRODUCER_IDENTITY_JSON');
const out=resolve(outputArg),linux=resolve(linuxArg),api=await installed(resolve(installArg)),root=process.cwd();
mkdirSync(out,{recursive:false});
const identity=json(identityArg),build=json(join(api.package,'dist/execution/source-build.json'));
for(const entry of build.inputs)assert.equal(sha(readFileSync(join(root,entry.path))),entry.sha256,`integrated input: ${entry.path}`);
for(const entry of build.outputs)for(const base of [api.package,linux])assert.equal(sha(readFileSync(join(base,entry.path))),entry.sha256,`output: ${base}/${entry.path}`);
verifyInstallation(api.package,identity.installed);
const sourceSha=spawnSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).stdout.trim();
const artifact={kind:'reused exact accepted independently installed product',producer:identity.candidate,integratedSource:sourceSha,installation:api.root,linux,producerIdentity:file(identityArg),sourceArchive:identity.archive,package:identity.package,sourceBuild:file(join(api.package,'dist/execution/source-build.json')),sourceInputsMatched:build.inputs.length,compiledOutputsMatched:build.outputs.length,installedFilesMatched:identity.installed.length,linuxRuntimeIdentity:api.validation.describeImproveRuntime(linux),environment:json(join(linux,'eval-environment.json'))};
save(join(out,'artifact.json'),artifact);
const fixturePath=join(root,'docs/implementation/pi-durio-v1/issue-30/improve-fixture.json'),fixture=json(fixturePath),workspace=join(out,'improve-project'),dataRoot=join(out,'improve-data');mkdirSync(workspace);
for(const [path,bytes]of Object.entries(fixture.files)){assert.equal(sha(bytes),fixture.fileHashes[path]);writeFileSync(join(workspace,path),bytes,{flag:'wx'});}
const transport=api.offline.scriptedTransport([{name:'bash',args:{command:`'${process.execPath.replaceAll("'","'\\''")}' check.mjs`}}]);
const seed=await api.runtime.runCodingTask({workspace,dataRoot,input:'Synthetic provenance seed only: execute the existing clamp check and preserve its first failure. Do not change any file. This scripted task is not real model inference.',mode:'offline',transport:transport.fetch});
save(join(out,'seed-result.json'),seed);save(join(out,'seed-requests.json'),transport.calls);
const records=(await api.runtime.readRun(dataRoot,seed.runId,{limit:200})).records;save(join(out,'seed-records.json'),records);
assert.equal(seed.cleanup,'confirmed');assert.match(JSON.stringify(transport.calls),/AssertionError/);
for(const [path,bytes]of Object.entries(fixture.files))assert.equal(readFileSync(join(workspace,path),'utf8'),bytes);
const trialIds=['local-fix','multi-file','regression','no-change'].map(caseId=>({id:`v1-live-r1-${caseId}`,caseId,side:'candidate',repeat:1,pair:null}));
const evalRoot=join(out,'eval-data');
const stage=await api.eval.prepareEval({dataRoot:evalRoot,id:'v1-live-r1-preparation-only',purpose:'Offline content staging only; never run. Exact proposed live trials require separate paid grant.',mode:'offline',installation:linux,cases:json(join(root,'docs/implementation/pi-durio-v1/issue-30/cases.json')),trials:trialIds,budget:{maxRequests:32,maxTokens:2000000,maxRequestTokens:1052672,deadline:'2099-01-01T00:00:00.000Z',unknownUpperBound:{tokens:1052672,source:'https://api-docs.deepseek.com/api/list-models/'}},trialTimeoutMs:300000,gradingTimeoutMs:30000,maxOutputTokens:4096,paid:false,price:{version:'DeepSeek-public-2026-10-09-maximum-class',source:'https://api-docs.deepseek.com/quick_start/pricing/',currency:'USD',perMillionTokens:1.2}});
const proposed=structuredClone(stage.plan);proposed.id='pi-durio-v1-live-r1';proposed.mode='live';proposed.purpose='One fixed real-provider representative batch; four single trials, no performance or population stability claim';proposed.authorization.paid=false;proposed.budget.deadline=null;
const request={id:'v1-live-r1-improve',purpose:'Analyze the retained failed clamp check and the explicitly registered project sources. Explain the observed defect and propose a minimal deterministic repair only if supported by acquired evidence. Only clamp.ts may be proposed for change; README.md, check.mjs and package.json are protected. No performance improvement is claimed. Return your own structured candidate, or zero candidates with the actual gaps. This is analysis only; user selection is separate.',limits:{maxRequests:8,maxTokens:2000000,maxRequestTokens:1056768,maxDurationMs:300000,maxOutputTokens:8192},sources:[{id:'clamp-project',kind:'project',paths:['clamp.ts','check.mjs','README.md','package.json']}],query:{maxRuns:1,maxRecords:50,maxEvidenceBytes:32768,maxSourceBytes:32768}};
api.improve.validateImproveRequest(request,'live');
const proposal={status:'PENDING_EXPLICIT_HUMAN_GRANT; not an executable paid plan',batchId:proposed.id,artifact:file(join(out,'artifact.json')),evalPlan:proposed,evalDataRoot:evalRoot,evalDirectory:join(out,'live-eval'),improve:{request,workspace,dataRoot,targetRunId:seed.runId,seed:file(join(out,'seed-result.json')),allowedWriteback:fixture.allowedWriteback,protected:fixture.protected},aggregate:{maxRequests:40,maxTokens:4000000,maximumListedUsdPerMillionTokens:1.2,conservativePriceEstimateUsd:4.8,requestedUsdCeiling:5,accountBill:'Not observed; token-price estimate only'},window:{grantToStartMs:86400000,activeMs:3600000,starts:1,definition:'One start within 24 hours of grant; immutable deadline start+60 minutes, including both stages. No resume or replacement batch after interruption or expiry.'},credential:{environment:'DEEPSEEK_API_KEY',source:'PENDING_USER_SPECIFIED_LOCAL_SOURCE',readiness:'NOT READ; no authentication attempted'},stops:['401/403 blocks next dispatch irrespective of body/usage','budget/response-bound/deadline violation or unknown usage without trusted reservation','model/endpoint unavailable or current tariff above stated estimate','source/runtime/fixture identity or ownership/isolation mismatch','eval hard FAIL or invalid/unknown trial: retain remaining not-run; no extra analysis','zero/invalid/incomplete improve report: retain, no extra analysis','cancel/interruption/cleanup unknown: no implicit resume'],futureSelection:'No candidate is prefilled or selected. Actual report/candidate revision, target baseline/content/check/writeback proposal must return to human.'};
save(join(out,'proposed-batch.json'),proposal);save(join(out,'preparation-summary.json'),{status:'PREPARED_NOT_AUTHORIZED',artifact,seedRunId:seed.runId,firstFailedCheck:'actual public runtime bash check; AssertionError retained in original tool output; all fixture bytes unchanged',proposed:file(join(out,'proposed-batch.json')),syntheticSeed:true,paidRequests:0});
console.log(JSON.stringify({status:'PREPARED_NOT_AUTHORIZED',proposal:join(out,'proposed-batch.json'),sourceSha,producer:identity.candidate,seedRunId:seed.runId}));
